elasticsearch:
  image: elasticsearch:5.2
  command: elasticsearch -Enetwork.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/ --verbose
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  env_file:
    - development.env
  ports:
    - "5000:5000"
  ports:
    - "5044:5044"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  environment:
    ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
  links:
    - elasticsearch
