logstash:
  image: logstash:2.3
  command: logstash -f /etc/logstash/conf.d/ --allow-env --verbose
  log_driver: syslog
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /data/logstash:/var/lib/logstash
  environment:
    ELASTICSEARCH_ENDPOINT: ${ELASTICSEARCH_ENDPOINT}
  ports:
    - "5000:5000"
  ports:
    - "5044:5044"
kibana:
  build: kibana/
  log_driver: syslog
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "80:5601"
  environment:
    ELASTICSEARCH_ENDPOINT: ${ELASTICSEARCH_ENDPOINT}
